# This is a basic workflow to help you get started with Actions

name: PowerShell

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: before checkout
        run: ls
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: after checkout
        env:
          SLACK_WEBHOOK_URI: ${{ secrets.SLACK_WEBHOOK_URI }}
        run: |
            cd ps
            pwd
            $res = Invoke-Pester -OutputFormat NUnitXml -PassThru
            $failcount = [int]$res.FailedCount
            $okcount = [int]$res.PassedCount
            $payload = "{`"failcount`":`"$failcount`", `"okcount`":`"$okcount`", `"username`":`"${{github.actor}}`"}"
            Invoke-RestMethod -Method Post -Uri ${{ secrets.SLACK_WEBHOOK_URI }} -Body $payload -ContentType "application/json"



      
